### PR TITLE
Eloquent support

### PR DESCRIPTION
**Pull request by theseankelly**
Porting project forward to Eloquent.

Fortunately no code changes to the core of `ros2_dotnet` were required; only some updates to repos, an update to the repos files, and updated build instructions.

This PR depends on the completion of #41 which should be merged first. I will rebase this PR once that happens.

### CODE REVIEW

**Comment by fmrico** [comment]
Great!!!! 

Thanks for your work ;)

**Comment by theseankelly** [comment]
Unfortunately it appears the `foonathan/memory` project (a new dependency of Fast-RTPS introduced in Eloquent) is currently unable to cross compile for ARM at the moment.

I've decided to disable ARM support for the near term as ARM on UWP is not very common -- I'll create a new issue to track finding an ARM-compatible DDS implementation (especially on ARM64 for HoloLens2) but in the meantime this will let work on the core ros2_dotnet project continue.

**Comment by theseankelly** [comment]
Experiencing quite a bit of trouble outside of Win32 builds -- closing PR until this is fully tested and ready on all platforms.

**Comment by fmrico** [comment]
Hi @theseankelly 

I have been building and testing this morning this branch in Linux, including rclcpp (I will need it for tf2). 

- I had to disable tests in dotnet because of an error similar to [this](https://answers.ros.org/question/315189/fail-at-ros2-idl-generation/).
- At `Fast-RTPS/src/cpp/transport/UDPv4Transport.cpp:313` I had to change `interface()` to `interface_name()`. I will prepare a PR with this.

I will try this afternoon to compile it in Win Desktop.

**Comment by theseankelly** [comment]
Oh, thanks for looking at this @fmrico -- I'll re-open the PR since you're working with it also.

Sounds good -- the bulk of my problems are with some new dependencies added by Fast-RTPS that are not UWP compatible. That, and I think the GitHub Actions environment is different in some ways as I don't have the same problems building locally.

**Comment by theseankelly** [comment]
Turns out the issues were due to known problems with the Fast-RTPS release for Eloquent -- updated the ros2-dotnet fork of Fast-RTPS.

**Comment by esteve** [comment]
@theseankelly the Fast-RTPS folks don't test their releases for all the platforms they claim to support, so this will be a recurring problem. I've opened https://github.com/ros2-dotnet/ros2_dotnet/issues/52 to investigate if we could get rid of Fast-RTPS and use CycloneDDS instead.

**Pull request merged**
