### PR TITLE
Build as an overlay on Windows/Linux

### LINKED ISSUE #51: Improve build instructions for Windows Desktop and Linux
The build instructions for Windows and Linux Desktop aren't ideal -- in particular on these platforms it shouldn't be necessary to compile the entire distribution. Rather, set the project up as an overlay workspace on top of an existing ROS2 installation.

For example, look at how the rust language bindings operate: They only build the core binding package itself, plus any relevant packages containing message IDLs (for message type generation): https://github.com/esteve/ros2_rust

### LINKED ISSUE #53: Problems building for Win10-Desktop
Hi,

I am building in Windows10 for Desktop, and I have found some problems:

- `ros2lifecycle` has a test dependency with `ros2lifecycle_test_fixtures`, and it depends on `rclcpp` and `rclcpp_lifecycle`. As @theseankelly and I discussed, it's better to avoid including `rclcpp`.
- `rcl_logging_spdlog` depends on `splog_vendor`, but it is not included in repos.
- `ros2trace` fails for a `UnicodeDecodeError:`

The build is successful if I compile with this line:

```
colcon build --merge-install --packages-ignore ros2lifecycle_test_fixtures rcl_logging_spdlog  ros2trace --cmake-args -DBUILD_TESTING=OFF -DRCL_LOGGING_IMPLEMENTATION=rcl_logging_noop
```

Building commands in CI already include some of these options, but in the instructions in README.md for building Desktop only says to build with `colcon build --merge-install`

@theseankelly Do you think that we should change the build instructions in readme.md? In any case, I don't know if it is recommendable to go without tests...

### LINKED ISSUE #55: Build error on Windows 10 dekstop
Hi, managed to run the build, but not sure why i am encountering this error
rcldotnet_common [ Exited with code 1 ]
towards the end of the build; and the rest of the rcldotnet_examples, rosidl_generator_dotnet all are not built.

`

Starting >>> rcl_yaml_param_parser
Failed <<< rcldotnet_common [ Exited with code 1 ]
Aborted <<< rosidl_generator_dds_idl
Aborted <<< rcpputils
Aborted <<< rcl_logging_spdlog
Aborted <<< rcl_yaml_param_parser
Aborted <<< rcl_logging_log4cxx
Aborted <<< rcl_logging_noop
Aborted <<< rosidl_generator_c
Summary: 87 packages finished [2min 10s]
1 package failed: rcldotnet_common
7 packages aborted: rcl_logging_log4cxx rcl_logging_noop rcl_logging_spdlog rcl_yaml_param_parser rcpputils rosidl_generator_c rosidl_generator_dds_idl
60 packages not processed
`

### PR DESCRIPTION
**Pull request by theseankelly**
- Updated repos file to build as an overlay
- Upated build instructions
- Created a Linux build workflow

Closes #51 
Closes #53 
Closes #55

### CODE REVIEW

**Comment by theseankelly** [comment]
Ugh building in CI has been one of the most frustrating topics...I've been testing over in my private fork for over a week (with all passes yesterday) and all I did differently was submit a PR. I'll keep working on it I guess.

https://github.com/theseankelly/ros2_dotnet/actions

**Comment by esteve** [comment]
@theseankelly is there anything I can help with?

**Comment by theseankelly** [comment]
@esteve thanks, but I don't think so -- in theory it should be straightforward. I think GitHub Actions is inserting some entropy just to troll me.

**Comment by theseankelly** [comment]
Wow, talk about poor timing.

The Windows runner for GitHub actions was refreshed very recently, which updated the default system Python to 3.7.7. It looks like the `ros-tooling/setup-ros` action hardcodes Python 3.7.6, which is now broken.

I [filed a bug](https://github.com/ros-tooling/setup-ros/issues/156) on the `ros-tooling/setup-ros` action, but its easily worked around by configuring python 3.7.6 prior to invoking the `ros-tooling/setup-ros` action.

Looks like the `Build (Desktop)` job has made it farther this time -- fingers crossed.

**Comment by esteve** [comment]
@theseankelly yay, the desktop runner passed! Thanks

**Comment by esteve** [comment]
@theseankelly is this ready for review or you'd rather way for the fix in `ros-tooling/setup-ros`

**Comment by theseankelly** [comment]
Let's go ahead with the review as-is.

**Pull request merged**
