### PR TITLE
Update to Foxy, Support Services, QoS, Tf2 via rclcpp and Hololens

### PR DESCRIPTION
**Pull request by ooeygui**

### CODE REVIEW

**Comment by esteve** [comment]
@ooeygui thanks for the PR. I had a brief look at it, but it's really difficult to review a PR this big which touches so many things at the same time and adds multiple features, could you break it down to individual PRs? Thanks.

Also, depending on `rclcpp` is a huge departure from the original goal of `ros2-dotnet`, I honestly don't see any major reason for doing so, client libraries in ROS2 are meant to be built upon `rcl`

**Comment by ooeygui** [comment]
As many of these are interconnected, splitting them out is not feasible at the moment.

**Comment by ooeygui** [comment]
Several useful features are built on rclcpp, which is why we added that component.

**Comment by ooeygui** [comment]
I'd be happy to schedule an virtual live review if that would help get through this PR.

**Comment by esteve** [comment]
> As many of these are interconnected; I'll see what we can do to split it out.

@ooeygui these features were added as separate PR in your fork, so it should be straightforward to replicate that onto upstream. For example, QoS was introduced in https://github.com/ms-iot/ros2_dotnet/pull/2, why not just resubmit that PR onto this repository? It's ok if PRs depend on each other, as long as they have a clear goal and can be discussed in isolation.

There are over 3000 additions in this PR, it's a massive diff, I'm quite sure if someone in your team sent a PR this it wouldn't go through easily.

> I'd be happy to schedule an virtual live review if that would help get through this PR.

Thanks, but let's try going the usual route, a live review of over 3000 additions is gonna be quite intense.

**Comment by ooeygui** [comment]
@esteve Please forgive my miscommunication about the license. Microsoft *by default* will contribute new code under MIT, but I have verified that Apache is fine as well. As I break up the original code drop in #84, I'll rewrite the license headers so that it is not mentioned. I have left PR 84 for the conversation history; however, if you want to close it to keep the noise down in the repo, that's fine too. 
I will remove the rclcpp binary as part of breaking up #84. 

I'm planning on addressing the CI issues independently first; I did see you had made progress on the Linux side; I'll build off that for Windows and UWP. 

Thank you

> moving to #84 as requested in #89

**Comment by ooeygui** [comment]
Converted this to a draft so it isn't accidentally pulled.

**Comment by pabloinigoblasco** [comment]
Hello.
What is the state of this today?

**Comment by hoffmann-stefan** [comment]
Closing this as it is out of sync with the main branch by merging my two PRs:
- #89
- #90 

QoS is already implemented in #94 if someone want's to checkout this branch, should be split out into a seperate PR in the next weeks.

For TF2 we have a separate repository that binds to the c++ classes. TF2 should not be part of the core `rcldotnet` library, but rather be it's own library that builds on top of `rcldotnet`. Think this will get moved to ros2_dotnet organization at some time.
- https://github.com/schiller-de/tf2_dotnet

**Pull request closed without merging**
