### PR TITLE
Collection types

### PR DESCRIPTION
**Pull request by fmrico**
Hi @esteve ,

This PR implements collections. It depends on PR #10 

Best

### CODE REVIEW

**Comment by esteve** [comment]
Thanks. Same comment as in https://github.com/esteve/ros2_dotnet/pull/10#issuecomment-458934283

**Comment by esteve** [comment]
@fmrico do you plan to add fixed-sized arrays and constraints?

**Comment by esteve** [comment]
@fmrico any update on supporting the rest of the collection types?

**Comment by esteve** [comment]
@fmrico ping

**Comment by fmrico** [comment]
@esteve pong

Yes, I am planning to support the rest of the collection types, but now all my efforts are focused on the tests in #10 . I will have to rebase this branch when #11 finishes.

Best

**Comment by esteve** [comment]
@fmrico do you plan to continue working on this? Thanks.

**Comment by fmrico** [comment]
Hi @esteve . Yes, I am planning to finish this.

**Comment by esteve** [comment]
@fmrico I've made this PR a draft, let us know when you'll be working on this again. Thanks.

**Comment by fmrico** [comment]
Hi @esteve 

I have been working on this for the last two weeks. I hope to PR something soon ;)

Best

**Pull request closed without merging**
