### PR TITLE
Add support for sequences/arrays of basic/primitive types (#1)

### PR DESCRIPTION
**Pull request by ooeygui**
Breaking up our large drop. This is support for arrays and primitive types

### CODE REVIEW

**Comment by esteve** [comment]
@ooeygui awesome! Thanks for breaking up the other PR, makes it so much easier to review.

**Comment by ooeygui** [comment]
Looking into the build failures

**Comment by esteve** [comment]
@ooeygui a priori changes look good, but I can't see the build logs. I'm going to approve this PR, but if you have time, it'd be great if you could fix the build issues before merging. Thanks!

**Review by esteve — APPROVED** [review]

**Comment by esteve** [comment]
@ooeygui how would you like to proceed here? Did you figure out what is causing the build issue? I created #86 to address the CI issues, but it seems `colcon` can't figure out the topological order of the packages.

**Comment by ooeygui** [comment]
Sorry for the delay (I've been heads down on getting the Foxy sync release stable on Windows).

**Comment by hoffmann-stefan** [comment]
Closing this PR as the features where implemented in https://github.com/ros2-dotnet/ros2_dotnet/pull/89 which is already merged.

**Pull request closed without merging**
